backend:
  name: git-gateway
  branch: production # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "public/uploads" # Media files will be stored in the repo under public/uploads
public_folder: "/uploads"

collections:
  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: {{slug}}
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "project"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Cover Image", name: "cover_image", widget: "image"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Technologies", name: "tech", widget: "string"}
      - {label: "Link", name: "link", widget: "string"}